### ISSUE TITLE
Translation - Remove #. comments

### ISSUE THREAD

**Issue by bovirus** [jrathlev/InnoUnpacker-Windows-GUI#21]
@jrathlev 

Coiuld you please consider to remove from translation source code reference?
Not usefull in translation and sometimes change UI reference buit not contents (strings) of language files.

**Comment by jrathlev** [comment]
The comments with the references to the source code are automatically generated by DxGetText ([see here](https://github.com/jrathlev/GnuGetText-for-Delphi)) and are very helpful for the programmer when backtracking errors, for example. 
If the po files are edited with [PoEdit](http://poedit.sourceforge.net/download.php), all comments are hidden and do not interfere with the translation.

In order to remove all automatically generated comments from a _po_ file, I have
provided a small program which is located in _languages/tool_.
